# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications
# SARIF, the Static Analysis Results Interchange Format, is a standard,
# JSON-based format for the output of static analysis tools.

name: Node.js Scan SARIF

on:
  push:
    branches: [test, master, release, main]

  pull_request:
    # The branches below must be a subset of the branches above
    branches: [test, master, release, main]

  schedule:
    - cron: "29 12 * * 6"

permissions:
  contents: read

jobs:
  njsscan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    runs-on: ubuntu-latest

    name: njsscan code scanning

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: ". --sarif --output results.sarif || true"

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
